Feature support lammps data files
votca/csg pull request #263
Opened 2018-07-31 17:52 UTC by JoshuaSBrown

2018-07-31 18:35 UTC, junghans requested changes
And convert tabs to spaces everywhere!

2018-07-31 18:35 UTC, junghans commented on include/votca/csg/topologyreader.h
> +    /// open a trajectory file
I guess topology file.

2018-07-31 18:35 UTC, junghans commented on src/libcsg/modules/io/lammpsdatareader.h
> +				std::map<std::string,std::vector<std::vector<std::string>>> data_;
Indentation screwed up

2018-07-31 18:35 UTC, junghans commented on src/libcsg/modules/io/lammpsdatareader.cc
> +			getline(fl_, line);
I guess you should free all the helper structures here!

2018-08-04 05:14 UTC, JoshuaSBrown commented
@junghans I think I have addressed your comments but take a look.

2018-08-04 19:22 UTC, junghans approved these changes

2018-08-05 15:07 UTC, merged