Electrostatics joshs development
votca/csg pull request #355
Opened 2019-03-30 01:51 UTC by JoshuaSBrown

2019-04-14 19:41 UTC, JensWehner commented
I need more info....

2019-04-14 19:49 UTC, JensWehner commented on include/votca/csg/bead.h
> +  int getResnr() const {
deprecated features are not removed features. If you want to deprecate a feature put the 

https://en.cppreference.com/w/cpp/language/attributes

attribute then

2019-04-14 19:50 UTC, JensWehner commented on include/votca/csg/beadlist.h
>  #include <list>
I think we can remove that include

2019-04-14 19:52 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  virtual void Apply(const BoundaryCondition *boundaries,
why pointers and not references

2019-04-14 19:52 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  virtual void Initialize(const std::vector<std::string> subbeads,
no const copy please

2019-04-14 19:52 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +                          std::vector<double> weights,
why all these copies

2019-04-14 19:52 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  void Initialize(std::vector<std::string> subbeads,
same here

2019-04-14 19:54 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  void Apply(const BoundaryCondition *boundaries,
Can you use a more descriptive name than Apply. Why not have a return value, i.e the cg bead?

2019-04-14 19:54 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  void AddElem(std::string atomic_bead_name, double weight,
what does this function do

2019-04-14 19:54 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  Map_Sphere() {}
why is constructor hidden?

2019-04-14 19:54 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +inline void Map_Sphere::AddElem(std::string atomic_bead_name, double weight,
why inline and not .cc file

2019-04-14 19:55 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  friend class AtomToCGMoleculeMapper;
why friend class

2019-04-14 19:56 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  AtomToCGMoleculeMapper(){};
why different constructors

2019-04-14 19:56 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  ~AtomToCGMoleculeMapper();
why explicit destructor?

2019-04-14 19:56 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  void Initialize(std::unordered_map<std::string, CGBeadStencil> bead_maps_info,
why passing by value?

2019-04-14 19:57 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +
same here

2019-04-14 19:57 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +  void Apply(CSG_Topology &atom_top, CSG_Topology &cg_top,
apply is not a very descriptive name

2019-04-14 19:58 UTC, JensWehner commented on include/votca/csg/beadmap.h
> +   * @brief Note that the gang of 3 must be explicity defined because the bead
it is gang of 5 now, do you not need move constructors and assignment operators

2019-04-14 19:58 UTC, JensWehner commented on include/votca/csg/beadmotifconnector.h
>      boost_bimap;
more descriptive name than that

2019-04-14 19:59 UTC, JensWehner commented on include/votca/csg/beadmotifconnector.h
> +  void AddMotifAndBeadEdge(tools::Edge motif_edge, tools::Edge bead_edge);
why copies

2019-04-14 19:59 UTC, JensWehner commented on include/votca/csg/beadmotifconnector.h
> +  std::vector<tools::Edge> getBeadEdges(tools::Edge motif_edge);
again

2019-04-14 19:59 UTC, JensWehner commented on include/votca/csg/beadpair.h
> +  BeadPair(Bead *bead1, Bead *bead2, Eigen::Vector3d r)
why pointers and not references?

2019-04-14 20:01 UTC, JensWehner commented on include/votca/csg/beadstructure.h
> +  const T *getBeadConst(int id) const;
use same name as above, the signature is different that is enough

2019-04-14 20:02 UTC, JensWehner commented on include/votca/csg/beadtriple.h
> +#include <votca/tools/vec.h>
remove

2019-04-14 20:02 UTC, JensWehner commented on include/votca/csg/beadtriple.h
> +  BeadTriple(Bead *bead1, Bead *bead2, Bead *bead3, Eigen::Vector3d r12,
why pointers?

2019-04-14 20:03 UTC, JensWehner commented on include/votca/csg/boundarycondition.h
> +  const Eigen::Matrix3d &getBox() { return box_; };
should also be a const function

2019-04-14 20:03 UTC, JensWehner commented on include/votca/csg/boundarycondition.h
> +      const Eigen::Vector3d &r_i, const Eigen::Vector3d &r_j) const {
no make it a pure virtual function

2019-04-14 20:03 UTC, JensWehner commented on include/votca/csg/boundarycondition.h
> +    throw std::runtime_error("getBoxType is not implemented.");
same here

2019-04-14 20:04 UTC, JensWehner commented on include/votca/csg/boundarycondition.h
> +      const Eigen::Vector3d &r_i, const Eigen::Vector3d &r_j) const {
you are creating a runtime error, where before you got a compiler error. That is not good

2019-04-14 20:05 UTC, JensWehner commented on include/votca/csg/cgengine.h
> +  CGEngine(){};
remove

2019-04-14 20:05 UTC, JensWehner commented on include/votca/csg/cgengine.h
> +  ~CGEngine(){};
remove

2019-04-14 20:06 UTC, JensWehner commented on include/votca/csg/cgengine.h
> +inline bool CGEngine::IsIgnored(std::string molecule_type) {
make function const

2019-04-14 20:07 UTC, JensWehner commented on include/votca/csg/cginteractionstencil.h
>   * limitations under the License.
this connection is weird

2019-04-14 20:07 UTC, JensWehner commented on include/votca/csg/cginteractionstencil.h
>   * limitations under the License.
growriter to interaction stencil

2019-04-14 20:08 UTC, JensWehner commented on include/votca/csg/cgmoleculestencil.h
> +
why explicit destructor?

2019-04-14 20:09 UTC, JensWehner commented on include/votca/csg/cgmoleculestencil.h
> +  void AddBeadStencil(const std::vector<CGBeadStencil> &bead_info);
you add more than one so AddBeadStencils

2019-04-14 20:11 UTC, JensWehner commented on include/votca/csg/csgtopology.h
> +class CSG_Topology : public TemplateTopology<Bead, Molecule> {
what do we need the template topology for?

2019-04-14 20:13 UTC, JensWehner commented on include/votca/csg/exclusionlist.h
> +class CSG_Topology;
I still do not get the renaming

2019-04-14 20:13 UTC, JensWehner commented on include/votca/csg/exclusionlist.h
>      std::list<Bead *> _exclude;
why a list?

2019-04-14 20:14 UTC, JensWehner commented on include/votca/csg/exclusionlist.h
>      std::list<Bead *> _exclude;
pointless datatype

2019-04-14 20:15 UTC, JensWehner commented on include/votca/csg/fileformatfactory.h
> +  std::unique_ptr<T> Create(const std::string &file);
nice

2019-04-14 20:16 UTC, JensWehner commented on include/votca/csg/interaction.h
> +  virtual double EvaluateVar(const BoundaryCondition &bc,
why unordered map?

2019-04-14 20:18 UTC, JensWehner commented on include/votca/csg/io/dlpolytopologyreader.h
> +/*
How many different topologies do we really need?

2019-04-14 20:18 UTC, JensWehner commented on include/votca/csg/io/dlpolytopologyreader.h
> +/*
I am not sure the whole templating is necessary here, we only have the csg_topology

2019-04-14 20:20 UTC, JensWehner commented on include/votca/csg/io/pdbwriter.h
> +  void RegisteredAt(
why this function?

2019-04-14 20:21 UTC, JensWehner commented on include/votca/csg/io/pdbwriter.h
> +    return item.getId() + 1;
why +1?

2019-04-14 20:22 UTC, JensWehner commented on include/votca/csg/io/pdbwriter.h
> +inline void PDBWriter<Bead_T, Molecule_T, Topology_T>::WriteContainer(
I do not undderstand this method, why do we have so many template parameters here

2019-04-14 20:23 UTC, JensWehner commented on include/votca/csg/io/pdbwriter.h
> +void PDBWriter<Bead_T, Molecule_T, Topology_T>::Write(boost::any conf_any) {
what is with this boost::any

2019-04-14 20:24 UTC, JensWehner commented on include/votca/csg/molecule.h
> +  friend class CSG_Topology;
why friend class?

2019-04-14 20:24 UTC, JensWehner commented on include/votca/csg/molecule.h
> +  std::unordered_set<int> bead_ids;
why the change?

2019-04-14 20:26 UTC, JensWehner commented on include/votca/csg/openbox.h
> +  virtual std::unique_ptr<BoundaryCondition> Clone() const override {
why a clone function?

2019-04-14 20:27 UTC, JensWehner commented on include/votca/csg/openbox.h
> +  virtual std::unique_ptr<BoundaryCondition> Clone() const override {
and not a simple copy constructor?

2019-04-14 20:27 UTC, JensWehner commented on include/votca/csg/orthorhombicbox.h
> +  virtual std::unique_ptr<BoundaryCondition> Clone() const override {
why virtual?

2019-04-14 20:29 UTC, JensWehner commented on include/votca/csg/templatetopology.h
> +  void Copy(const TemplateTopology<Bead_T, Molecule_T> &top);
why not simply a copy constructor?

2019-04-14 20:30 UTC, JensWehner commented on include/votca/csg/templatetopology.h
> +  std::list<Interaction *> InteractionsInGroup(const std::string &group) const;
why list?

2019-04-14 20:31 UTC, JensWehner commented on include/votca/csg/templatetopology.h
> +    throw std::runtime_error(
make pure virtual function

2019-04-14 20:31 UTC, JensWehner commented on include/votca/csg/templatetopology.h
> +        "CreateMolecule must be overwritten by derived type it may not be "
again

2019-04-14 20:33 UTC, JensWehner commented on include/votca/csg/topologyreader.h
> +  virtual bool ReadTopology(std::string file, boost::any top) { return false; }
why not a pure virtual function

2019-04-14 20:33 UTC, JensWehner commented on include/votca/csg/topologyreader.h
>    static void RegisterPlugins(void);
delete

2019-04-14 20:34 UTC, JensWehner commented on include/votca/csg/topologytypecontainer.h
> +  TopologyTypeContainer(){};
why explicit constructor?

2019-04-14 20:39 UTC, JensWehner requested changes

2019-04-14 20:39 UTC, JensWehner commented on include/votca/csg/trajectoryreader.h
> +  virtual bool Open(const std::string &file){};
make them virtual functions

2019-04-14 20:39 UTC, JensWehner commented on include/votca/csg/trajectoryreader.h
> +        "Cannot call FirstFrame using Trajectory reader it must be derived by "
virtual functions

2019-04-14 20:39 UTC, JensWehner commented on include/votca/csg/trajectoryreader.h
> +    throw std::runtime_error(
again

2019-04-14 20:39 UTC, JensWehner commented on include/votca/csg/trajectorywriter.h
> +  virtual void Write(boost::any top) = 0;
what is that boost::any? I really do not like this datatype

2019-04-14 20:39 UTC, JensWehner commented on include/votca/csg/triclinicbox.h
> +  virtual std::unique_ptr<BoundaryCondition> Clone() const override {
why virtual?

2019-05-04 06:29 UTC, JoshuaSBrown commented
The trajectory and topology classes cannot have pure virtual methods. This is the error I get if I try. I think it is because you cannot call new on an abstract data type because it is not well defined, I quote

"You cannot instantiate an abstract class."

Error: 

In file included from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/../fileformatfactory.h:25:0,
                 from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/../topologyreader.h:24,
                 from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/groreader.h:22,
                 from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/topologyreader.cc:23:
/usr/local/include/votca/tools/objectfactory.h: In instantiation of ‘parent* votca::tools::create_policy_new() [with parent = votca::csg::TopologyReader; T = votca::csg::XYZReader<votca::csg::CSG_Topology>]’:
/usr/local/include/votca/tools/objectfactory.h:101:11:   required from ‘void votca::tools::ObjectFactory<key_t, T>::Register(const key_t&) [with obj_t = votca::csg::XYZReader<votca::csg::CSG_Topology>; key_t = std::__cxx11::basic_string<char>; T = votca::csg::TopologyReader]’
/home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/topologyreader.cc:40:61:   required from here
/usr/local/include/votca/tools/objectfactory.h:89:10: error: invalid new-expression of abstract class type ‘votca::csg::XYZReader<votca::csg::CSG_Topology>’
   return new T();
          ^~~~~~~
In file included from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/topologyreader.cc:27:0:
/home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/xyzreader.h:45:7: note:   because the following virtual functions are pure within ‘votca::csg::XYZReader<votca::csg::CSG_Topology>’:
 class XYZReader : public TrajectoryReader, public TopologyReader {
       ^~~~~~~~~
In file included from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/groreader.h:22:0,
                 from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/topologyreader.cc:23:
/home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/../topologyreader.h:36:16: note: 	virtual bool votca::csg::TopologyReader::ReadTopology(std::__cxx11::string, boost::any)
   virtual bool ReadTopology(std::string file, boost::any top) = 0;
                ^~~~~~~~~~~~
In file included from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/../fileformatfactory.h:25:0,
                 from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/../trajectoryreader.h:22,
                 from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/dlpolytrajectoryreader.h:34,
                 from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/trajectoryreader.cc:23:
/usr/local/include/votca/tools/objectfactory.h: In instantiation of ‘parent* votca::tools::create_policy_new() [with parent = votca::csg::TrajectoryReader; T = votca::csg::XYZReader<votca::csg::CSG_Topology>]’:
/usr/local/include/votca/tools/objectfactory.h:101:11:   required from ‘void votca::tools::ObjectFactory<key_t, T>::Register(const key_t&) [with obj_t = votca::csg::XYZReader<votca::csg::CSG_Topology>; key_t = std::__cxx11::basic_string<char>; T = votca::csg::TrajectoryReader]’
/home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/trajectoryreader.cc:47:61:   required from here
/usr/local/include/votca/tools/objectfactory.h:89:10: error: invalid new-expression of abstract class type ‘votca::csg::XYZReader<votca::csg::CSG_Topology>’
   return new T();
          ^~~~~~~
In file included from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/trajectoryreader.cc:29:0:
/home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/xyzreader.h:45:7: note:   because the following virtual functions are pure within ‘votca::csg::XYZReader<votca::csg::CSG_Topology>’:
 class XYZReader : public TrajectoryReader, public TopologyReader {
       ^~~~~~~~~
In file included from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/groreader.h:22:0,
                 from /home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/trajectoryreader.cc:25:
/home/jbrown/Documents/Software/VOTCA/csg/src/libcsg/../../include/votca/csg/io/../topologyreader.h:36:16: note: 	virtual bool votca::csg::TopologyReader::ReadTopology(std::__cxx11::string, boost::any)
   virtual bool ReadTopology(std::string file, boost::any top) = 0;
                ^~~~~~~~~~~~

2019-05-17 15:39 UTC, JensWehner requested changes
I am not done yet, but in general the use of very intricate structures makes it very hard to understand the code.

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  AtomCGConverter(){};
why?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  void Convert(CSG_Topology &atomic_top_in, CSG_Topology &cg_top_out);
why not use a return type, input topolgy should be const

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  void Map(CSG_Topology &atomic_top_in, CSG_Topology &cg_top_out);
why not call it update if it updated one of the topologies should be const

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  std::map<int, std::map<int, std::vector<std::pair<std::string, int>>>>
this is not a nice object, maybe use a structure or a class?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  std::unordered_set<std::string> file_names_;
why not a vector?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  void ConvertAtomisticMoleculeToCGAndAddToCGTopology_(
waht is a CGT topology why not use a return type?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  void ConvertAtomisticMoleculeToCGAndAddToCGTopology_(
atom top should probably be const.

Should this method not be two separate ones?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  void CheckThatBeadCountAndInteractionTypeAreConsistent_(
should that not return a bool?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  void ParseMaps_(
what kind of Maps?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  void ParseMaps_(
why no return type?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  std::map<int, std::vector<std::pair<std::string, int>>> CreateMolecule_(
why no return type? The name of the function is misleading

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  std::map<int, std::vector<std::pair<std::string, int>>> CreateBeads_(
misleading fucntion name which returns a large construct

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +  void CreateInteractions_(
I cannot figure out what is input and output, const qualifiers would help

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/basebead.h
> +  tools::Identity<int> molecule_id_;
Identity is not a good name, what does it mean?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/basemolecule.h
> +  std::unordered_set<int> getBeadIdsByName(const std::string &name) const;
why an unordered_set and not  a vector?

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/basemolecule.h
> +  std::unordered_set<int> getBeadIdsByType(const std::string &name) const;
I do not understand the use of unordered_set

2019-05-17 15:39 UTC, JensWehner commented on include/votca/csg/basemolecule.h
> +  std::unordered_set<int> getBeadIdsByType(const std::string &name) const;
why not simply a vector

2019-06-06 10:48 UTC, JensWehner commented on include/votca/csg/atomcgconverter.h
> +#include <list>
why include list

2019-06-18 19:29 UTC, JoshuaSBrown commented
Still need tests for topolgy type container, dlpoly file readers and writers.

2019-09-17 01:55 UTC, junghans commented
ping @JoshuaSBrown

2019-10-18 16:00 UTC, JoshuaSBrown commented
This pull request was kept open for all the review comments which are addressed in https://github.com/votca/csg/pull/381 I believe they have been addressed now closing.

2019-10-18 16:00 UTC, closed without merging