added time-dependent box size
votca/csg pull request #363
Opened 2019-04-03 17:57 UTC by junghans

Fix #361 
Fix #362

2019-04-03 17:58 UTC, junghans commented
@AditiKhot please test this patch!

2019-04-03 18:15 UTC, JoshuaSBrown requested changes
Also address the Codacy issue raised.

2019-04-03 18:15 UTC, JoshuaSBrown commented on src/libcsg/modules/io/h5mdtrajectoryreader.cc
> +  double *data_out = new double[3];
Is there anyway we can avoid using new and raw pointers here?

2019-04-03 18:15 UTC, JoshuaSBrown commented on src/libcsg/modules/io/h5mdtrajectoryreader.cc
> +  double *data_out = new double[3];
maybe declare unique_ptr and pass data_out.get() to H5Dread, then you don't need to worry about deleting it later.

2019-04-03 18:39 UTC, junghans commented
Can you take a shot at it?

2019-04-04 16:23 UTC, JoshuaSBrown commented
So, we do not yet have support for make_unique in std c++11 I think, hence the error. You will have to use unique_ptr<>() instead of make_unique<>().

2019-04-04 16:25 UTC, junghans commented
@JoshuaSBrown can you do a pass?

2019-04-04 16:30 UTC, JoshuaSBrown commented
Ok, but you will owe me a cider, I'm not a big beer drinker.

2019-04-04 16:57 UTC, JensWehner commented
I thought we are on c++14 now?

2019-04-04 16:57 UTC, JensWehner commented
ahh no stable is still c++11

2019-04-04 17:01 UTC, JensWehner approved these changes
if it is c++11 compliant it looks good

2019-04-04 19:13 UTC, JoshuaSBrown approved these changes

2019-04-04 20:14 UTC, jkrajniak approved these changes

2019-04-04 22:09 UTC, merged

2019-04-04 23:00 UTC, AditiKhot commented
> @AditiKhot please test this patch!

I get this error when I recompile votca:
namespace "std" has no member "make_unique"

2019-04-05 00:13 UTC, AditiKhot commented
> > @AditiKhot please test this patch!
> 
> I get this error when I recompile votca:
> namespace "std" has no member "make_unique"

I think I was using wrong files. However, I still get an error as below while compiling

`In file included from /depot/bsavoie/apps/VOTCA/votca/csg/include/votca/csg/beadlist.h(23),
                 from /depot/bsavoie/apps/VOTCA/votca/csg/src/libcsg/beadlist.cc(18):
/depot/bsavoie/apps/VOTCA/votca/csg/include/votca/csg/topology.h(434): error: no instance of constructor "votca::csg::Bead::Bead" matches the argument list
            argument types are: (votca::csg::Topology *, std::size_t, std::string, votca::tools::byte_t, std::string, int, double, double)
        Bead *b = new Bead(this, _beads.size(), type, symmetry, name, resnr, m, q);
                          ^
/depot/bsavoie/apps/VOTCA/votca/csg/include/votca/csg/bead.h(44): note: this candidate was rejected because mismatch in count of arguments
  class Bead : public TopologyItem
        ^
/depot/bsavoie/apps/VOTCA/votca/csg/include/votca/csg/bead.h(386): note: this candidate was rejected because arguments do not match
      Bead(Topology *owner, int id, BeadType *type, byte_t symmetry, string name, int resnr, double m, double q)
      ^

compilation aborted for /depot/bsavoie/apps/VOTCA/votca/csg/src/libcsg/beadlist.cc (code 2)
`
Thank you for the help!

2019-04-05 00:29 UTC, junghans commented
@AditiKhot don't worry the patch already got merged in `stable`, so can do https://github.com/votca/votca/blob/master/share/doc/INSTALL.md#general-source-installation-instructions with `version=stable`, or wait until #364 is merged and you can use `master` as well.

2019-04-06 01:24 UTC, AditiKhot commented
I tried using stable version, but I get the above error.