Standardize the include format
votca/csg pull request #531
Opened 2020-05-15 05:45 UTC by JoshuaSBrown

2020-05-15 15:14 UTC, junghans requested changes

2020-05-15 15:14 UTC, junghans commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/include/votca/csg>
I think we don.'t need that line.

2020-05-15 15:14 UTC, junghans commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include/votca/csg>
And this is only need if we want to use the public header without `votca/csg` prefix in our tools. Do we want that?

2020-05-15 15:19 UTC, junghans commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include/votca/csg>
I think you did a look of `#include "../../votca/csg/foo.h`, so that should be needed.

2020-05-17 21:35 UTC, JoshuaSBrown commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include/votca/csg>
No we definitely want the full prefix.

2020-05-17 21:37 UTC, JoshuaSBrown commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include/votca/csg>
Why do we want these lines in xtp then?

2020-05-17 23:10 UTC, junghans commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include/votca/csg>
I made a comment in xtp, the one line is unnecessary there, too.

The other one is needed as `votca_config.h` is a public header in xtp, but in csg it is private. (Not sure why it needs to be public in xtp)

2020-05-17 23:10 UTC, junghans commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include/votca/csg>
I made a comment in xtp, the one line is unnecessary there, too.

The other one is needed as `votca_config.h` is a public header in xtp, but in csg it is private. (Not sure why it needs to be public in xtp)

2020-05-18 00:17 UTC, JoshuaSBrown commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include/votca/csg>
ooh, ok so I do need this line because of the config file:

```
 $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/include/votca/csg>
```

2020-05-18 00:20 UTC, junghans approved these changes

2020-05-18 00:33 UTC, junghans commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include/votca/csg>
In xtp, but not csg.

2020-05-18 00:33 UTC, junghans commented on src/libcsg/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include/votca/csg>
For the xtp votca_config.h only, xtp doesn't know about csg's votca_config.h

2020-05-18 08:01 UTC, JensWehner approved these changes

2020-05-18 11:55 UTC, merged