Switch to unique_ptrs
votca/csg pull request #653
Opened 2021-02-11 06:21 UTC by JoshuaSBrown

Part 3

2021-02-11 16:34 UTC, JensWehner commented on include/votca/csg/topologymap.h
> +  using MapContainer = std::vector<std::unique_ptr<Map>>;
why not just make it

```suggestion
  using MapContainer = std::vector<Map>;
```

2021-02-11 16:34 UTC, JensWehner commented on include/votca/csg/topologymap.h
> +  using MapContainer = std::vector<std::unique_ptr<Map>>;
and make it value based.

2021-02-11 16:35 UTC, JensWehner requested changes
either use `make_unique` or preferably make it value based and not pointer based

2021-02-12 01:58 UTC, junghans commented
@JoshuaSBrown 
```
/__w/csg/csg/votca/csg/include/votca/csg/topologymap.h:52:33: error: no matching function for call to 'std::vector<votca::csg::Map>::push_back(std::remove_reference<std::unique_ptr<votca::csg::Map>&>::type)'
   52 |   _maps.push_back(std::move(map));
      |                                 ^
```

2021-02-12 03:54 UTC, junghans commented
No app using the mapping fail:
```
	 92 - integration_Run_csg_fmatch (SEGFAULT)
	 94 - integration_Run_csg_fmatch_3body (SEGFAULT)
	100 - integration_Run_csg_map_gro (SEGFAULT)
```

2021-02-12 06:16 UTC, JoshuaSBrown commented
Might need to wait until the topology map pr gets merged before this will work.

2021-02-14 10:52 UTC, JensWehner commented on include/votca/csg/map.h
> +  friend class Map;
I do not understand.

2021-02-14 10:53 UTC, JensWehner requested changes
I do not understand the hiding of all the constructors. I understand that you want to protect certain conditions, but in my mind that is what assert statements are for. I do not want to couple constructors to other classes, even less friend them, because then encapsulation goes out of the window. 

If you want to create a common interface for object creation, I would make a factory.

2021-02-23 06:44 UTC, JoshuaSBrown commented
> I do not understand the hiding of all the constructors. I understand that you want to protect certain conditions, but in my mind that is what assert statements are for. I do not want to couple constructors to other classes, even less friend them, because then encapsulation goes out of the window.
> 
> If you want to create a common interface for object creation, I would make a factory.

Ok, I think I can make that work, I'll just move all the child classes into the source files, that should hide them from being used where they are not supposed to.

2021-02-26 04:19 UTC, junghans commented
@votca-bot format

2021-02-26 07:47 UTC, JensWehner approved these changes
thanks

2021-02-26 07:47 UTC, merged